let teams=[],matches=[],standings=[],isAdmin=false;
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Hata');return d}
function logo(src,name){return src?`<img class="miniLogo" src="${src}" alt="">`:`<div class="miniLogo placeholder">LOGO</div>`}
async function load(){[teams,matches,standings]=await Promise.all([api('/api/teams'),api('/api/matches'),api('/api/standings')]); renderStandings();renderFixtures();renderTeams();renderAdmin();loadPlayoffs();}
function renderStandings(){ $('#standingsBody').innerHTML=standings.map(t=>`<tr><td>${t.pos}</td><td><div class="teamCell">${logo(t.logo,t.name)}<span>${esc(t.name)}</span><span class="badge ${t.status==='DIRECT'?'direct':t.status==='PLAYOFF'?'play':'out'}">${t.status==='DIRECT'?'DİREKT':t.status==='PLAYOFF'?'PLAYOFF':'ELENDİ'}</span></div></td><td>${t.played}</td><td>${t.win}</td><td>${t.draw}</td><td>${t.loss}</td><td>${t.gd}</td><td><b>${t.pts}</b></td></tr>`).join('')}
function renderFixtures(){const sel=$('#weekSelect');sel.innerHTML='<option value="all">Tüm haftalar</option>'+[1,2,3,4,5,6,7,8].map(w=>`<option value="${w}">${w}. Hafta</option>`).join(''); const draw=()=>{const f=sel.value==='all'?matches:matches.filter(m=>m.week==sel.value);const groups={};f.forEach(m=>(groups[m.week]??=[]).push(m));$('#fixturesList').innerHTML=Object.entries(groups).map(([w,arr])=>`<div class="week">${w}. HAFTA</div>`+arr.map(m=>`<div class="match"><div class="side">${logo(m.home_logo,m.home_name)}<span>${esc(m.home_name)}</span></div><div class="score">${m.home_score==null?'—':m.home_score+' : '+m.away_score}</div><div class="side away"><span>${esc(m.away_name)}</span>${logo(m.away_logo,m.away_name)}</div></div>`).join('')).join('')||'<div class="note">Bu seçimde maç bulunmuyor.</div>'};sel.onchange=draw;draw()}
function renderTeams(){const q=($('#teamSearch').value||'').toLocaleLowerCase('tr-TR');$('#teamGrid').innerHTML=teams.filter(t=>t.name.toLocaleLowerCase('tr-TR').includes(q)).map(t=>`<div class="teamCard">${t.logo?`<img src="${t.logo}">`:'<div class="teamCard placeholder">LOGO YOK</div>'}<b>${esc(t.name)}</b></div>`).join('')}
$('#teamSearch').oninput=renderTeams;
async function loadPlayoffs(){const ps=await api('/api/playoffs');const rounds=['PLAYOFF','ROUND OF 16','QUARTERFINAL','SEMIFINAL','FINAL'];const labels={'PLAYOFF':'PLAYOFF (9–24)','ROUND OF 16':'SON 16','QUARTERFINAL':'ÇEYREK FİNAL','SEMIFINAL':'YARI FİNAL','FINAL':'FİNAL'};$('#bracket').innerHTML=rounds.map(r=>{const arr=ps.filter(x=>x.round===r);return `<div class="round"><h3>${labels[r]}</h3>${arr.map(x=>`<div class="pair"><span>${esc(x.team1_name||'Bekleniyor')}</span><b>${x.score1==null?'—':x.score1+' : '+x.score2}</b><span>${esc(x.team2_name||'Bekleniyor')}</span></div>`).join('')}</div>`}).join('')}
async function checkAdmin(){isAdmin=(await api('/api/me')).admin;$('#loginBox').classList.toggle('hidden',isAdmin);$('#adminBox').classList.toggle('hidden',!isAdmin);if(isAdmin)renderAdmin();}
function renderAdmin(){if(!isAdmin)return;$('#adminMatches').innerHTML=matches.map(m=>`<div class="adminMatch"><span>${m.week}. ${esc(m.home_name)} – ${esc(m.away_name)}</span><input id="h${m.id}" type="number" min="0" value="${m.home_score??''}"><input id="a${m.id}" type="number" min="0" value="${m.away_score??''}"><button class="ghost" onclick="saveMatch(${m.id})">Kaydet</button></div>`).join('');$('#adminTeams').innerHTML=teams.map(t=>`<div class="adminTeam"><span style="width:24px">${logo(t.logo,t.name)}</span><input id="n${t.id}" type="text" value="${esc(t.name)}"><input id="f${t.id}" type="file" accept="image/*"><button class="ghost" onclick="saveTeam(${t.id})">Kaydet</button></div>`).join('')}
window.saveMatch=async id=>{await api('/api/matches/'+id,{method:'PUT',body:JSON.stringify({home_score:$('#h'+id).value,away_score:$('#a'+id).value})});await load()};
window.saveTeam=async id=>{await api('/api/teams/'+id,{method:'PUT',body:JSON.stringify({name:$('#n'+id).value})});const f=$('#f'+id).files[0];if(f){const fd=new FormData();fd.append('logo',f);await fetch('/api/teams/'+id+'/logo',{method:'POST',body:fd})}await load()};
$('#login').onclick=async()=>{try{await api('/api/login',{method:'POST',body:JSON.stringify({password:$('#password').value})});$('#password').value='';await checkAdmin()}catch(e){$('#loginError').textContent=e.message}};
$('#logout').onclick=async()=>{await api('/api/logout',{method:'POST'});await checkAdmin()};
$('#adminBtn').onclick=async()=>{$('#adminModal').classList.remove('hidden');await checkAdmin()};$('#closeAdmin').onclick=()=>$('#adminModal').classList.add('hidden');
$('#generatePlayoffs').onclick=async()=>{await api('/api/playoffs/generate',{method:'POST'});await loadPlayoffs();alert('Playoff eşleşmeleri mevcut puan sıralamasına göre oluşturuldu.')};$('#refreshPlayoffs').onclick=loadPlayoffs;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
load();
